name:  Github App

on:  
  push:
  workflow_dispatch:
  
jobs:
  checkout:
    runs-on: ubuntu-latest
    permissions:
      contents: read
       
    steps:
      - name:  checkout repo
        uses:  actions/checkout@v4
        with:
          token:  ${{secrets.GITHUB_TOKEN}}
          repository:  AnuTestOrg/Testrepo1
          
      - name:  Github App Token
        uses:  actions/create-github-app-token@v1
        id:  app-token
        with:
          app-id:  ${{vars.APP_ID}}
          private-key:  ${{secrets.PRIVATE_KEY}}
          repositories:  "Testrepo2"
          owner: ${{ github.repository_owner }}

      - name:  use token
        env:  
          TOKEN: ${{ steps.app-token.outputs.token }}
        run:  |
          echo 'The generated token is masked: ${TOKEN}'
        
      - name:  checkout private repo
        uses:  actions/checkout@v3
        with:
          token:  ${{ steps.app-token.outputs.token }}
          repository:  AnuTestOrg/Testrepo2
          path:  Testrepo2
          # token:  ${{secrets.GH_PAT}}
          ref: 'main'
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
          
      # - uses: AnuTestOrg/Testrepo2@main
      #   with:
      #     github_token: ${{ steps.app-token.outputs.token }}

      - name:  Show Contents
        run:  ls -lR
    
