name:  Github App

on:  [workflow_dispatch]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout repo
        uses:  actions/checkout@v3
        with:
          token:  ${{secrets.GITHUB_TOKEN}}
          path:  AnuTestOrg/Testrepo1

      - name:  checkout private repo
        uses:  actions/checkout@v3
        with:
          token:  ${{secrets.GITHUB_TOKEN}}
          path:  AnuTestOrg/Testrepo2
    
