name:  Github App

on:  [workflow_dispatch]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name:  checkout repo
        uses:  actions/checkout@v4
        with:
          token:  ${{secrets.GITHUB_TOKEN}}
          repository:  AnuTestOrg/Testrepo1
          
      - name:  Github App Token
        uses:  actions/create-github-app-token@v1
        id:  app-token
        with:
          app-id:  ${{vars.APP_ID}}
          private-key:  ${{secrets.PRIVATE_KEY}}
        
      - name:  checkout private repo
        uses:  actions/checkout@v4
        with:
          token:  ${{steps.app-token.outputs.token}}
          repository:  AnuTestOrg/Testrepo2
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false
    
