name: list of apps

on:
  push:
  workflow_dispatch:
    # inputs:
    #   app:
    #   description: 'Repository to register'
    #   required: true

jobs:
  apps:
    runs-on: ubuntu-latest
    steps:
    
      - name:  Github App Token
        uses:  actions/create-github-app-token@v1
        id:  app-token
        with:
          app-id:  ${{vars.APP_ID}}
          private-key:  ${{secrets.PRIVATE_KEY}}
          owner: ${{ github.repository_owner }} 
          
      - name: Rest Api
        run: |
          gh api /orgs/AnuTestOrg/installations
        env:
          GH_TOKEN: ${{secrets.APP_PAT}}
        # env:
        #   GH_TOKEN: ${{ steps.app-token.outputs.token }}
          
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: GitHub Apps data
      #     path: app.json
      #     if-no-files-found: error
